# Generated by Django 3.2.25 on 2024-12-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
